name: Run AAC Script Daily

on:
  schedule:
    - cron: '0 1 * * *' # Run daily at 1:00 AM UTC
  workflow_dispatch: # Enable manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install dependencies in a virtual environment
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          python3 -m pip install selenium selenium-wire requests
          python3 -m pip show requests  # Show requests details to verify it's installed

      # Step 4: Verify Python Environment
      - name: Verify Python Environment
        run: |
          which python3
          python3 --version
          which pip  # Check if pip is correctly linked to virtualenv

      # Step 5: Run the script
      - name: Run AAC Script
        run: |
          source venv/bin/activate  # Activate virtual environment
          python3 aac_urls_full_auto.py
