name: Run AAC Script Daily

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install selenium selenium-wire requests

      # Step 4: Run the script
      - name: Run AAC Script
        run: |
          python3 aac_urls_full_auto.py
